# Programación para Análisis de datos
## Práctica 3: Numpy



<b>Nota:</b>
Esta practica esta basada en algunos de los ejercicios presentes en https://github.com/rougier/numpy-100.

numpy-100: Version 1.1
Nicolas P. Rougier; Jessica B. Hamrick; ibah; Gavin Heverly-Coulson; Dapid; Christoph Deil; Bartosz Telenczuk

<hr>

#### Importa el paquete numpy con el nombre np

In [2]:
import numpy as np
import random

#### Imprime la versión de numpy

In [7]:
np.version.version

'1.26.1'

#### Crea un vector nulo de tamaño 10

In [6]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Crea un vector nulo de tamaño 10, pero el quinto valor es 1

In [9]:
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Crea un vector con valores enteros del 10 al 49

In [23]:
v1=np.arange(10, 50)

In [25]:
v1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Invierte el vector anterior, usando indexación (el primer elemento se convierte en el último)

In [26]:
v2=v1[::-1]


In [29]:
v2

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### Muestra los elementos de las posiciones impares de arreglo anterior. Usa indexación.

In [28]:
v2[1:len(v1):2]

array([48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16,
       14, 12, 10])

#### Crea un vector con valores del 0 al 8 y transformalo en una matriz 3x3

In [179]:
mat=np.arange(9).reshape(3,3)

In [192]:
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Seleccionar un fila

In [180]:
mat[0]

array([0, 1, 2])

In [182]:
mat[0,:]

array([0, 1, 2])

#### Seleccionar columnas

In [190]:
mat[:,1]

array([1, 4, 7])

In [193]:
mat[:,(0,2)]

array([[0, 2],
       [3, 5],
       [6, 8]])

#### Crea una matriz de identidad 3x3

In [34]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Crea un array con la siguiente matriz:

1 5 7\
2 5 3\
1 2 3

In [35]:
np.matrix('1 5 7; 2 5 3; 1 2 3')

matrix([[1, 5, 7],
        [2, 5, 3],
        [1, 2, 3]])

#### Crea un array 3x3 con valores aleatorios. Documentación: https://numpy.org/doc/stable/reference/random/generator.html#

In [37]:
np.random.rand(3,3)

array([[0.66863993, 0.92660016, 0.58030132],
       [0.72791438, 0.76765452, 0.33505218],
       [0.26358382, 0.03679672, 0.32286286]])

#### Crea un array 10x10 con valores aleatorios y encuentra los valores mínimo y máximo

In [42]:
v4=np.random.rand(10,10)
v4

array([[0.81484611, 0.04814409, 0.76173826, 0.59839892, 0.43989373,
        0.76154675, 0.27694652, 0.63731648, 0.01764035, 0.94399983],
       [0.63548635, 0.17997177, 0.36941687, 0.7380502 , 0.34360091,
        0.6245335 , 0.36225743, 0.69653682, 0.42318601, 0.09452189],
       [0.77590252, 0.7854158 , 0.68247982, 0.16303255, 0.96888232,
        0.34242464, 0.89521621, 0.7917522 , 0.70420938, 0.74237826],
       [0.49595661, 0.71887658, 0.97747992, 0.99854965, 0.73943857,
        0.96395959, 0.51599068, 0.41905259, 0.75978198, 0.40861896],
       [0.75095919, 0.8777022 , 0.22972147, 0.62824156, 0.63516798,
        0.70710472, 0.80315185, 0.54192816, 0.45103696, 0.23705504],
       [0.66429227, 0.0812807 , 0.71411672, 0.46131949, 0.9368945 ,
        0.82067542, 0.83917973, 0.57351745, 0.73033025, 0.65991772],
       [0.49720576, 0.36558894, 0.5277303 , 0.83433385, 0.3278146 ,
        0.00998894, 0.56846092, 0.75289603, 0.25701659, 0.23254076],
       [0.84340957, 0.36731342, 0.1637135

In [197]:
# Intersección de las filas 2 y 3 con las columnas 2 y 3
v4[2:4,2:4]

array([[0.68247982, 0.16303255],
       [0.97747992, 0.99854965]])

In [43]:
np.max(v4)

0.998549645038399

In [44]:
np.min(v4)

0.006149408843798332

#### Crea un vector aleatorio de tamaño 30 y encuentra el valor promedio

In [47]:
v5=np.random.rand(30)

In [49]:
v5

array([0.66123733, 0.46955117, 0.67344966, 0.50737762, 0.41419457,
       0.09459238, 0.16170034, 0.76318738, 0.18993557, 0.41115871,
       0.15837715, 0.921388  , 0.73691891, 0.64994754, 0.96373157,
       0.0774498 , 0.84686072, 0.81301862, 0.1808973 , 0.51815778,
       0.51744484, 0.94204624, 0.67387123, 0.55974524, 0.12206113,
       0.46877899, 0.24384042, 0.97095518, 0.13606528, 0.30891546])

In [48]:
np.mean(v5)

0.5052285363456083

#### ¿Cuál son los resultados de las siguientes expresiones? Que significan nan e inf (busca en la documentación)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [198]:
# nan es un elemento nulo, inf representa infito positivo 
# en el ultimo es el problema de los floats con la precision, si usamos round la indentidad es verdadera

In [55]:
round(0.3) == round(3 * 0.1)

True

In [199]:
0 * np.nan

nan

#### Crea una matriz 5x5 con valores 1,2,3,4 justo debajo de la diagonal

In [62]:
matrix = np.diag([1, 2, 3, 4], k=-1)
matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### Crea una matriz 8x8 y llénala con un patrón de tablero de ajedrez. Luego haz lo mismo pero para una matriz de 16x16

In [64]:
np.tile([[1,0],[0,1]], (4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [66]:
np.tile([[1,0],[0,1]], (8,8))

array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

#### Multiplica una matriz aleatoria de 5x3 por una matriz aleatoria de 3x2

In [67]:
np.matmul((np.random.rand(15).reshape(5,3)),(np.random.rand(15).reshape(3,5)))

array([[0.45394705, 0.49780551, 0.15357312, 0.16120079, 0.43360406],
       [0.95071218, 1.07269819, 0.33552669, 0.43709096, 0.82005959],
       [1.11173106, 0.96850501, 0.42333076, 0.84040597, 1.29377294],
       [0.68901882, 0.70270907, 0.24082477, 0.32119126, 0.71394149],
       [1.30788588, 1.26463845, 0.51205242, 1.06025856, 1.29049613]])

#### Crea una matriz de 5x5 con valores enteros aleatorios entre 0 y 4

In [68]:
np.random.random_integers(1,4,size=(5,5))

/tmp/ipykernel_1631207/3839312606.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 4 + 1) instead
  np.random.random_integers(1,4,size=(5,5))


array([[4, 3, 2, 3, 3],
       [4, 4, 1, 3, 3],
       [2, 1, 2, 3, 4],
       [3, 2, 2, 3, 1],
       [2, 1, 1, 2, 4]])

In [71]:
np.random.randint(1,4,size=(5,5))

array([[3, 2, 2, 1, 1],
       [2, 1, 1, 3, 2],
       [1, 3, 2, 3, 2],
       [3, 3, 3, 2, 2],
       [2, 1, 2, 2, 3]])

#### Crea un vector aleatorio de 10 elementos y ordenalo de menor a mayor. Luego, invierte el orden con indexación.

In [75]:
v5=np.sort(np.random.rand(10))
v5

array([0.10713873, 0.14855364, 0.18903275, 0.19215331, 0.37229888,
       0.44293833, 0.47757177, 0.64988707, 0.76986805, 0.86575851])

In [76]:
v5[::-1]

array([0.86575851, 0.76986805, 0.64988707, 0.47757177, 0.44293833,
       0.37229888, 0.19215331, 0.18903275, 0.14855364, 0.10713873])

#### Crea un vector aleatorio de 100 elementos. Obtén la media, el desvío, la varianza, la mediana, el mínimo, máximo y el rango.

In [77]:
v6=np.random.rand(100)
v6_mean=np.mean(v6)
v6_std=np.std(v6)
v6_var=np.var(v6)
v6_med=np.median(v6)


#### Considera dos vectores aleatorios A y B, chequea si estos son completamente iguales. Pruebalo con vectores iguales, y luego modifica algún elemento en uno de ellos.

#### Crea un vector aleatorio de distribución normal de tamaño (100,2), representando coordenadas. Obtén las distancias de los 100 puntos al vector (0.5, 0.5) d=sqrt()


In [80]:
v8=np.random.randint(0,100,size=(100,2))
vv=[0.5,0.5]

In [86]:
for j in range(10):
    print(np.sqrt((v8[j,0]-0.5)**2+(v8[j,1]-0.5)**2))


9.82344135219425
80.61327434114061
84.25259639916149
87.70689824637512
48.5025772511111
104.51076499576492
86.29310517069136
83.357663115037
85.06762016184537
23.37733945512192


In [84]:
v8.shape

(100, 2)

#### Haz una función que dada una matriz cualquiera, normalice cada fila restando por la media y diviendo por el desvío. Pruebala

In [3]:
v9=np.arange(25).reshape(5,5)

In [4]:
np.median(v9, axis=1)

array([ 2.,  7., 12., 17., 22.])

In [141]:
v9

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [177]:
v9=np.arange(25).reshape(5,5)
normalized_matrix = np.zeros(25).reshape(5,5)
for i in range(5):
    median=np.median(v9[i])    
    std_dev=np.std(v9[i])
    normalized_row=(v9[i]-median)/std_dev
    normalized_matrix[i]=normalized_row
normalized_matrix

array([[-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356],
       [-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356],
       [-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356],
       [-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356],
       [-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356]])

In [150]:
def normalize_rows(matrix):
    row_means = np.mean(matrix, axis=1)
    row_stds = np.std(matrix, axis=1)
    normalized_matrix = (matrix - row_means[:, np.newaxis]) / row_stds[:, np.newaxis]
    return normalized_matrix
normalize_rows(v9)

array([[-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356],
       [-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356],
       [-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356],
       [-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356],
       [-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356]])

#### Haz una función que dada una matriz cualquiera, normalice cada columna restando por la media y diviendo por el desvío. Pruebala

In [178]:
v9=np.arange(25).reshape(5,5)
normalized_matrix = np.zeros(25).reshape(5,5)
for i in range(5):
    median=np.median(v9[:,i])    
    std_dev=np.std(v9[:,i])
    normalized_row=(v9[:,i]-median)/std_dev
    normalized_matrix[:,i]=normalized_row
normalized_matrix

array([[-1.41421356, -1.41421356, -1.41421356, -1.41421356, -1.41421356],
       [-0.70710678, -0.70710678, -0.70710678, -0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.70710678,  0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356,  1.41421356,  1.41421356]])

#### Toma un arreglo 1D cualquiera, y obtén una media movil con una ventana de 3 elementos.

In [201]:
array=np.arange(10)
np.convolve(array, [1, 1, 1], mode='valid') / 3


array([1., 2., 3., 4., 5., 6., 7., 8.])

#### Haz lo mismo, que en el inciso anterior, pero antes agrega 'padding' para que la salida sea del mismo tamaño que la entrada.

#### Toma un arreglo de enteros aleatorios del 0 al 100. Obtén el valor más frecuente.

In [5]:
v=np.random.randint(0,100,size=(10000))
counts=np.bincount(v)
print('El valor más frecuente es', np.argmax(counts), 'y se repite', np.max(counts), 'veces')

El valor más frecuente es 43 y se repite 121 veces


#### Dada una matriz aleatoria entera de 1000x3, con valores entre 0 y 10. Elimina las repeticiones de las filas, y obtén una versión filtrada.

In [41]:
v2=np.random.randint(0,10,size=(1000,3))

In [42]:
v2

array([[8, 1, 3],
       [8, 5, 8],
       [4, 1, 0],
       ...,
       [1, 4, 4],
       [5, 4, 1],
       [3, 1, 3]])

In [49]:
filtered_array = np.unique(v2, axis=1)
filtered_array


array([[1, 3, 8],
       [5, 8, 8],
       [1, 0, 4],
       ...,
       [4, 4, 1],
       [4, 1, 5],
       [1, 3, 3]])

In [55]:
t=np.arange(9).reshape(3,3)
t

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Select rows 0 and 1

In [59]:
t[(0,2),:]

array([[0, 1, 2],
       [6, 7, 8]])

In [61]:
# Select columns 1 and 2
t[:,(1,2)]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [64]:
#Select rows 0 and 1 and columns 1 and 2
t[(0,1),:][:,(1,2)]

array([[1, 2],
       [4, 5]])

In [65]:
#select 4
t[1,1]

4

In [68]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [69]:
b.sum(axis=0)

array([3, 3])

# Muchísimos ejercicios

Con solución: https://www.w3resource.com/python-exercises/numpy/index.php

Con ayudas: https://www.w3schools.com/python/numpy/exercise.asp

In [52]:
v3=np.array([[1,3,4,5],[0,0,8,8],[6,7,9,9],[4,5,6,7]])
np.unique(v3, axis=1)

array([[1, 3, 4, 5],
       [0, 0, 8, 8],
       [6, 7, 9, 9],
       [4, 5, 6, 7]])

In [71]:
v4=np.arange(10)
v4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
#hasta el 4 (excluido)
v4[:4]

array([0, 1, 2, 3])

In [77]:
# desde el 4 (incluido)
v4[4:]

array([4, 5, 6, 7, 8, 9])

In [78]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])